name: CI
on:
  push:
    branches: 
      - main
      - development

  pull_request:
    branches: 
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0 
        with:
          dotnet-version: 7.0.x
      
      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build
        run: dotnet build --no-restore
  
      - name: Run tests
        run: dotnet test
