name: deploy
on:
  push:
    branches: [ main, development ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0 
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Publish
        run: dotnet publish ./PooPosting.Api/PooPosting.Api.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
        
      - name: upload artifact
        uses: actions/upload-artifact@2.2.4
        with:
          name: api-artifact
          path: ${{ env.DOTNET_ROOT }}/api
 
 
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - name: download artifact
        uses: actions/download-artifact@2.1.1
        with:
          name: api-artifact
          
          
