name: Deploy Dev
run-name: ${{ github.actor }} odpalił
on:
  push:
    branches:
      - development
  workflow_dispatch:
concurrency:
  group: PooPosting
  cancel-in-progress: false
jobs:
  DeployDev:
    runs-on: ubuntu-latest
    steps:
      - name: Queue (kłełełe)
        uses: devkeydet/action-environment-queue@v1
        with:
          environment: PooPosting
          github-token: ${{ secrets.API_KEY_DEVOPS }}
      - run: echo "Udało się!"
      - name: Git repo
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{vars.DOTNET_VERSION}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Tests
        run: dotnet test --configuration Release --no-build
      - name: Zaciągnięcie skryptu python
        run: "wget https://raw.githubusercontent.com/PooPosting/DevOps/master/.github/workflows/varsManage.py -O .github/workflows/varsManage.py"
      - name: Zaciągnięcie pliku requirements
        run: "wget https://raw.githubusercontent.com/PooPosting/DevOps/master/.github/workflows/requirements.txt -O .github/workflows/requirements.txt" 
      - name: Uruchomienie skryptu python
        env:
          API_KEY_DEVOPS: ${{secrets.API_KEY_DEVOPS}}
          aktualizowac: "absolutnie"
        run: |
          python -m pip install --upgrade pip
          if [ -f .github/workflows/requirements.txt ]; then
            pip install -r .github/workflows/requirements.txt; 
          fi
          python -u .github/workflows/varsManage.py
      - name: Zaciągnięcie pliku appsettings
        run: "wget https://raw.githubusercontent.com/PooPosting/Back-end/development/PooPosting.Api/appsettings.Template.json -O .github/workflows/appsettings.json"
      - name: Wypełnianie pliku sekretami
        uses: faradaytrs/substitute-secrets-action@2.1
        with:
          input: .github/workflows/appsettings.json
          substitutionRegex: \$<([A-Z0-9_]+)>
          substitutionData: ${{ toJSON(secrets) }}
      - name: Zaciągnięcie playbooka
        run: "wget https://raw.githubusercontent.com/PooPosting/DevOps/master/backend-update.yml -O .github/workflows/backend-update.yml"
      - name: Run ansible playbook
        env:
          type: dev
          repo: development
          d_version: ${{vars.DOTNET_VERSION}}
        uses: dawidd6/action-ansible-playbook@master
        with:
          playbook: backend-update.yml
          directory: ./.github/workflows
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [vps]
            ${{ secrets.IP }}